"""
模块: formation_py（包入口）
职责: 暴露记忆形成算子、pipeline、profile 与 meta-controller。
输入: 无。
输出: FormationOperator、默认 operator、FormationResult 等类型。
副作用: 无。
失败处理: 无。
"""

from .controller import (
    IntentNormalizer,
    LLMIntentParser,
    LLMPlanParser as LLMPlanParserProtocol,
    MetaControllerResult,
    PlanDecisionTrace,
    RuleBasedMetaController,
    WorkspaceBriefBuilder,
)
from .llm_planner import (
    LLMClient,
    LLMMetaController,
    LLMPlanParser,
    LLMPlanProposal,
    LLMPlanStepProposal,
    LLMPlanValidator,
    LLMPlannerConfig,
    LLMPlannerPromptBuilder,
    LLMPlanningResult,
    OpenAICompatibleLLMClient,
)
from .meta_formation import (
    FormationEpisode,
    FormationEpisodeBuilder,
    LLMMetaMemoryReflector,
    MetaFormationIdFactory,
    MetaMemoryReflector,
    MetaMemoryUpdateCandidate,
    MetaMemoryUpdateDecision,
    RuleBasedMetaMemoryReflector,
    STAGE1_ENGINEERING,
    STAGE2_QA_DATASET,
    STAGE3_HUMAN_PREFERENCE,
    apply_review_decision,
)
from .meta_memory import (
    FormationMetaMemoryProvider,
    FormationMetaMemoryWriter,
    MetaMemoryApplyResult,
    MetaMemoryDeduper,
    MetaMemoryIndex,
)
from .operators import (
    AMemNoteOperator,
    CAMClusterOperator,
    ClusterFusionOperator,
    EvidencePreservingCompressor,
    FormationOperator,
    GistOperator,
    HeuristicGistOperator,
    LinkEvolutionOperator,
    OperatorRegistry,
    ProceduralExtractor,
    SemanticFactExtractor,
    SourceKindClusterOperator,
    create_default_registry,
)
from .pipeline import FormationPipeline, debug_plan, graph_plan, overview_plan
from .profile import DocumentRoleProfile, DocumentRoleProfiler, WorkspaceProfile, WorkspaceProfiler
from .types import (
    EvidenceSpan,
    FormationArtifact,
    FormationContext,
    FormationPlan,
    FormationResult,
    FormationRun,
    FormationStep,
    FormationTrace,
    DocumentSelector,
    OperatorSpec,
)

__all__ = [
    "AMemNoteOperator",
    "CAMClusterOperator",
    "ClusterFusionOperator",
    "DocumentSelector",
    "DocumentRoleProfile",
    "DocumentRoleProfiler",
    "EvidencePreservingCompressor",
    "EvidenceSpan",
    "FormationArtifact",
    "FormationContext",
    "FormationEpisode",
    "FormationEpisodeBuilder",
    "FormationMetaMemoryProvider",
    "FormationMetaMemoryWriter",
    "FormationOperator",
    "FormationPipeline",
    "FormationPlan",
    "FormationResult",
    "FormationRun",
    "FormationStep",
    "FormationTrace",
    "GistOperator",
    "HeuristicGistOperator",
    "IntentNormalizer",
    "LLMIntentParser",
    "LLMClient",
    "LLMMetaController",
    "LLMMetaMemoryReflector",
    "LLMPlanParser",
    "LLMPlanParserProtocol",
    "LLMPlanProposal",
    "LLMPlanStepProposal",
    "LLMPlanValidator",
    "LLMPlannerConfig",
    "LLMPlannerPromptBuilder",
    "LLMPlanningResult",
    "LinkEvolutionOperator",
    "MetaControllerResult",
    "MetaFormationIdFactory",
    "MetaMemoryApplyResult",
    "MetaMemoryDeduper",
    "MetaMemoryIndex",
    "MetaMemoryReflector",
    "MetaMemoryUpdateCandidate",
    "MetaMemoryUpdateDecision",
    "OperatorRegistry",
    "OperatorSpec",
    "OpenAICompatibleLLMClient",
    "PlanDecisionTrace",
    "ProceduralExtractor",
    "RuleBasedMetaController",
    "RuleBasedMetaMemoryReflector",
    "STAGE1_ENGINEERING",
    "STAGE2_QA_DATASET",
    "STAGE3_HUMAN_PREFERENCE",
    "SemanticFactExtractor",
    "SourceKindClusterOperator",
    "WorkspaceProfile",
    "WorkspaceProfiler",
    "WorkspaceBriefBuilder",
    "apply_review_decision",
    "create_default_registry",
    "debug_plan",
    "graph_plan",
    "overview_plan",
]
